### ISSUE TITLE
Crash after scanning QuickConnect Code

### ISSUE THREAD

**Issue by ChristopherA** [Fonta1n3/FullyNoded#10]
Using Fully Noded 1.82 (84), just after updating it in TestFlight, and after doing "Kill Switch" to reset data, I went to Nodes, +, then Scan QR. Crashed after scanning QR.

A possible clue, on relaunch, all the old default wallet data is back rather than being an empty wallet with no node, as if the Kill Switch didn't actually kill everything.

 I did submit a crash report through TestFlight.

**Comment by ChristopherA** [comment]
This immediate bug is gone, new one(s) are causing crashes after QR scan or shortly thereafter.

Deleted Fully Noded, reinstalled from TestFlight (now 1.83 (85)), updated BitcoinStandup.app to todays version (buggy version number in info — it says Version 1.0 (1)), went to add node, scanned QR code. It got further, saying there were two wallets on the node (testnet and ?) and I selected testnet. Fully Noded crashed. However, when I open Fully Noded after crash, my standup node was listed, and I could connect to it with Fully Noded. 

I deleted the app again to find out the name of that second wallet (testnet & ?), and did add node, but this time it crashed immediately after the QR scan, without asking me with wallet to choose. When I opened Fully Noded after crash my standup node was set and Fully Noded could communicate with it.

-- Christopher Allen

**Comment by Fonta1n3** [comment]
The "testnet" wallet is a wallet a user added on the "Tor Testing Node", if the testing node has multiple wallets loaded that your device does not know about it will prompt you to choose one. This is only because there are multiple people sharing the testing node, adding and loading wallets independently.

With regards to the crashes, I have made significant improvements to how the app interacts with core data in latest testflight release 1.86(88) - v0.1.21. Should be live on testflight tomorrow. Please do try again and let me know if you experience any crashes after that.
