### ISSUE TITLE
Fully Noded crashes on "verifying" step of creating transaction

### ISSUE THREAD

**Issue by watersnake1** [Fonta1n3/FullyNoded#101]
Using iOS 13.1.3, Fully Noded 0.1.81

I navigate to the wallet tab, where I am using a fully-noded wallet (not a default core wallet). Tap "send", put in the details of the transaction, tap the top right button. The "creating psbt" screen finishes loading, then the "verifying" screen shows up. After a few seconds, the app crashes.

**Comment by Fonta1n3** [comment]
Hey, is this on mainnet or testnet?

Would you mind using the testflight version to replicate this and then share the crash report? https://testflight.apple.com/join/a6GWxet2

Your wallets/nodes will persist across Testflight and App Store.

**Comment by watersnake1** [comment]
This was on main net. Just tried the TestFlight version and it happens there too.

**Comment by Fonta1n3** [comment]
@watersnake1 cool, did you share the crash report? And please let me know which device you are using so I can make sure I am looking at the correct crash report.

**Comment by Fonta1n3** [comment]
@watersnake1 just FYI if you need to spend, then you can try locking all but the one utxo you want to spend, then try and create the tx again as a way to troubleshoot.

**Comment by Fonta1n3** [comment]
I was able to replicate this using Bitcoin Core v0.19.1, the issue was that addresses labels are returned differently in older versions of Bitcoin Core (official supported version for FN is at least 0.20). 

v0.1.82 has been submitted to App Store, Mac App Store and TestFlight. Please do update and try again or in the meantime update Bitcoin Core to 0.20 if it is an urgent spend.

Thanks for reporting the bug.
