### ISSUE TITLE
Node settings aren't being saved

### ISSUE THREAD

**Issue by mcsnubbs** [Fonta1n3/FullyNoded#4]
I previously got this up and running on iOS and loved the program. However, after having to backup and restore my phone, the app lost all of the node settings. When I try to reconfigure my node, none of the information seems to be saving. For instance, after entering in all of the RPC data and going to the next screen, if I go BACK, none of the RPC information has been saved. If I complete all the node settings, it gives me an error that I cant connect to the node, and when I try to re-configure the node, again it shows blank information for all of the settings.

**Comment by niallyoung** [comment]
Sounds like where I got stuck.

**Comment by Fonta1n3** [comment]
Ah thats a great bug! It is caused by the device restore process. What I can do to fix it is add a "reset app" button in the settings which will completely reset the app and should solve your issue.

Unfortunately no data is saved to any server and I want to keep it that way. So you will have to manually add the credentials again after resetting the app.

I will add this feature for the next release and it should fix your issue. Unfortunately due to my location I wont be able to push that release until mid October.

Very pleased you were enjoying the app! Please keep an eye out for the next update and thanks for finding a good bug.

@niallyoung it does not sound like your issue as you did not do a device restore, if you are having an issue with the current version please open a new issue and I will help.

**Comment by mcsnubbs** [comment]
Great! Keep up the amazing work!

**Comment by Fonta1n3** [comment]
latest testflight update has a kill switch, use it, then force close and reopen the app. should fix your issue
